### ISSUE TITLE
EMS Student User Creation

### ISSUE THREAD

**Issue by vjbollavarapu** [vcs-asia/ICMS.EMS.User#1]
EMS supposed to create user id with the email that is provided for the student. But it is creating with some GUID. Please check the screenshot

![image](https://github.com/vcs-asia/ICMS.EMS.User/assets/16207415/03d27630-ca2d-4332-8009-835db9429cbd)

Reported by Sarvan.

**Comment by vjbollavarapu** [comment]
Automatic User Credentials occur in 2 places.

1. At the time of activating an applicant as a student
2. At the time of recreating user credentials.

Above both place we find no issue.

**Comment by SK1990101** [comment]
the reported issue is happening during the time of recreating user credentials.
for this 15-20 students i mentioned via email, they are all activated as a student. so i need to re-create to send the sms out.

**Comment by vjbollavarapu** [comment]
Thank you Sarvan. Please check the below screenshot. We have just restored settings related to User Creation. Below is the tested one.

![image](https://github.com/vcs-asia/ICMS.EMS.User/assets/16207415/0f5d7936-c8cc-4a4e-ae9a-770ad512adfd)

You too please test first from your side then close the issue. Thanks.

**Comment by vjbollavarapu** [comment]
> the reported issue is happening during the time of recreating user credentials.
> for this 15-20 students i mentioned via email, they are all activated as a student. so i need to re-create to send the sms out. 

I noted this. You need to have regular monitoring on the application.

**Comment by SK1990101** [comment]
Hi Vijay, thanks for the update here. I have tested for this SMS issue, the SMS is sent and receive correctly. but now for those some of the programme students with the credentials received unable to login. I think something is wrong with the "Student No" generation causing the EMS ID to have invalid character. Please check screenshot. 

![Untitled](https://github.com/vcs-asia/ICMS.EMS.User/assets/156168966/63ab9975-96c3-4395-aeef-5030202804e9)

**Comment by vjbollavarapu** [comment]
You need to correct the Programme short code which is supposed to have 3 characters. No special characters can be included in the first 3 characters. And it is based on the practice of ICMS registry. Please correct it

**Comment by SK1990101** [comment]
Just to confirm, so it should be something like the below screenshot instead?

Sorry, i wasn't aware of this. Will take note.

![Untitled1](https://github.com/vcs-asia/ICMS.EMS.User/assets/156168966/fd4729dc-3342-45e8-824e-9a37b32166b5)

**Comment by SK1990101** [comment]
This issue can be closed as well. The timetable issue i have closed. Thanks
