### ISSUE TITLE
EMS - Academic Calendar issue

### ISSUE THREAD

**Issue by SK1990101** [vcs-asia/ICMS.EMS.User#5]
As highlighted on 01/02/24, we are having issues on the Academic Calendar module to view.. I think it was okay earlier in January24..

**Comment by vjbollavarapu** [comment]
Please assign this too as well to Nabila

**Comment by SK1990101** [comment]
Hi Vijay, any updates???

**Comment by SK1990101** [comment]
Hi Vijay, i have tested this too. its visible now.
