### ISSUE TITLE
EMS - Changed Programme issue 

### ISSUE THREAD

**Issue by SK1990101** [vcs-asia/ICMS.EMS.User#6]
Another issue reported to Vijay on 01/02/24 the Changed Programme.. 

https://drive.google.com/file/d/1F7hzS-6Q1kYT6bwvwiJ3oOwSVdeVNcT9/view?usp=sharing

**Comment by vjbollavarapu** [comment]
Can you assign the issues to Nabila?

**Comment by SK1990101** [comment]
Vijay, i am not sure how to assign it to Nabila..

**Comment by SK1990101** [comment]
Hi Vijay, any updates???

**Comment by vjbollavarapu** [comment]
Please check your email on this issue.
